image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - iteration
  - release

default:
  cache:
    paths:
      - .cache/pip
  before_script:
    - python --version ; pip --version  # For debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install jira

add-iteration-job:
  stage: iteration
  script:
    - python scripts/add-iteration.py
  tags: [shared-podman]
  when: always

list-release-job:
  stage: release
  script:
    - python scripts/list-release.py
  tags: [shared-podman]
  when: always
